CosmeticsStore/Models/EF/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CosmeticsStore.Models.EF
{
    [Table("tb_Order")]
    public class Order: CommonAbstract
    {
        public Order() 
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public string Code { get; set; }
        [Required(ErrorMessage ="Tên khách hàng không được để trống")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage ="Số điện thoại không được để trống")]
        public string Phone { get; set; }
        [Required] 
        public string Email { get;set; }
        [Required(ErrorMessage ="Địa chỉ không được để trống")]
        public string Address { get; set; }

        public decimal TotalAmount { get; set; }
        public int Quantity { get; set; }
        public string IdUser { get; set; }
        public int TypePayment{ get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

CosmeticsStore/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CosmeticsStore.Models
{
    public class OrderViewModel
    {
        [Required(ErrorMessage = "Tên khách hàng không được để trống")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được để trống")]
        public string Phone { get; set; }
        [Required]
        public string Email { get; set; }
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        public string Address { get; set; }
        public int TypePayment { get; set; }
    }
}

CosmeticsStore/Areas/Admin/Controllers/OrderController.cs
using CosmeticsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Security.Policy;
using CosmeticsStore.Models.EF;
using OfficeOpenXml;
using System.Data.Entity;

namespace CosmeticsStore.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, StaffOrder")]
    public class OrderController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/Order
        public ActionResult Index(string Searchtext, int? page)
        {
            IEnumerable<Order> items = db.Orders.OrderByDescending(x => x.Id);
            var pageSize = 10;
            if (page == null)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Code.Contains(Searchtext) || x.CustomerName.Contains(Searchtext) || x.Phone.Contains(Searchtext));
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }

        public ActionResult View(int id)
        {
            var item = db.Orders.Find(id);
            return View(item);
        }

        public ActionResult Partial_SanPham(int id)
        {
            var items = db.OrderDetails.Where(x => x.OrderId == id).ToList();
            return PartialView(items);
        }

        [HttpPost]
        public ActionResult UpdateTT(int id, int trangthai)
        {
            var item = db.Orders.Find(id);
            if (item != null)
            {
                db.Orders.Attach(item);
                item.TypePayment = trangthai;
                db.Entry(item).Property(x => x.TypePayment).IsModified = true;
                db.SaveChanges();
                return Json(new { message = "Thành công", Success = true });
            }
            return Json(new { message = "Thất bại!", Success = false });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = db.Orders.Find(id);
            if (item != null)
            {
                db.Orders.Remove(item);
                db.SaveChanges();
                return Json(new { success = true });
            }

            return Json(new { success = false });
        }
        public void ExportExcel_EPPLUS()
        {
            // Thiết lập LicenseContext cho EPPlus
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            // Lấy danh sách Orders
            IEnumerable<Order> items = db.Orders.OrderBy(x => x.Id);

            using (ExcelPackage ep = new ExcelPackage())
            {
                // Tạo worksheet mới
                ExcelWorksheet Sheet = ep.Workbook.Worksheets.Add("Report");

                // Ghi tiêu đề cho các cột
                Sheet.Cells["A1"].Value = "STT";
                Sheet.Cells["B1"].Value = "Mã Đơn Hàng";
                Sheet.Cells["C1"].Value = "Tên Khách Hàng";
                Sheet.Cells["D1"].Value = "Số Điện Thoại";
                Sheet.Cells["E1"].Value = "Tiền";
                Sheet.Cells["F1"].Value = "Ngày Tạo";

                int row = 2; // dòng bắt đầu ghi dữ liệu
                int i = 1;

                // Duyệt qua danh sách đơn hàng và ghi vào Excel
                foreach (var item in items)
                {
                    Sheet.Cells[string.Format("A{0}", row)].Value = i;
                    Sheet.Cells[string.Format("B{0}", row)].Value = item.Code;
                    Sheet.Cells[string.Format("C{0}", row)].Value = item.CustomerName;
                    Sheet.Cells[string.Format("D{0}", row)].Value = item.Phone;
                    Sheet.Cells[string.Format("E{0}", row)].Value = item.TotalAmount;
                    Sheet.Cells[string.Format("F{0}", row)].Value = item.CreatedDate.ToString("dd/MM/yyyy");

                    row++;
                    i++;
                }

                // Tự động căn chỉnh độ rộng của các cột
                Sheet.Cells["A:AZ"].AutoFitColumns();

                // Gửi file về client
                Response.Clear();
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment; filename=DanhSachDonHang.xlsx");
                Response.BinaryWrite(ep.GetAsByteArray());
                Response.End();
            }
        }


    }
}

CosmeticsStore/Controllers/OrdersController.cs
using CosmeticsStore.Models;
using CosmeticsStore.Models.EF;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CosmeticsStore.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Orders
        public ActionResult Index(string Searchtext)
        {
            IEnumerable<Order> items = db.Orders.Where(x => x.Code == Searchtext);
            return View(items);
        }
        public ActionResult View(int id)
        {
            var item = db.Orders.Find(id);
            return View(item);
        }
        public ActionResult Partial_SanPham(int id)
        {
            var items = db.OrderDetails.Where(x => x.OrderId == id).ToList();
            return PartialView(items);
        }
        public ActionResult Refund()
        {
            return View();
        }
        public ActionResult ListOrders(string id)
        {
            id = User.Identity.GetUserId();
            if (id == null)
            {
                return View();
            }
            else
            {
                IEnumerable<Order> items = db.Orders.Where(x => x.IdUser == id);
                items = items.OrderByDescending(y => y.CreatedDate);
                return View(items);
            }
        }
        [HttpPost]
        public ActionResult UpdateTT(int id, int trangthai)
        {
            var item = db.Orders.Find(id);
            if (item != null)
            {
                db.Orders.Attach(item);
                item.TypePayment = trangthai;
                db.Entry(item).Property(x => x.TypePayment).IsModified = true;
                db.SaveChanges();
                return Json(new { message = "Thành công", Success = true });
            }
            return Json(new { message = "Thất bại!", Success = false });
        }
    }
}

CosmeticsStore/Areas/Admin/Views/Order/Index.cshtml
@model PagedList.IPagedList<CosmeticsStore.Models.EF.Order>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Danh sách đơn hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/home" class="nav-link"><font color="white">Trang chủ</font></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/order" class="nav-link"><font color="white">Danh sách đơn hàng</font></a>
        </li>
    </ul>
}
<!-- Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh sách đơn hàng</h3>
        </div>
        <div class="card-body">
            <div class="row" style="padding-bottom:15px">
                <div class="col-6">
                    <form>
                        @using (Html.BeginForm("index", "Orders", FormMethod.Get, new { }))
                        {
                            <div class="input-group input-group">
                                <input id="Searchtext" name="Searchtext" type="text" class="form-control" placeholder="Mã đơn hàng/Tên khách hàng/Số điện thoại">
                                @*<input type="text" name="searchText" class="form-control">*@
                                <span class="input-group-append">
                                    <button type="submit" class="btn btn-info">Tìm Kiếm</button>
                                </span>
                            </div>
                        }
                    </form>
                </div>
                <div class="col-6" style="text-align:right">
                    <a href="@Url.Action("ExportExcel_EPPLUS","Order")" class="btn btn-warning">Xuất Excel</a>
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Mã đơn hàng</th>
                        <th>Tên khách hàng</th>
                        <th>Số điện thoại</th>
                        <th>Tổng tiền</th>
                        <th>Trạng thái</th>
                        <th>Ngày đặt</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = ((ViewBag.Page - 1) * ViewBag.PageSize) + 1;
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@i</td>
                                <td>@item.Code</td>
                                <td>@item.CustomerName</td>
                                <td>@item.Phone</td>
                                <td>@CosmeticsStore.Common.Common.FormatNumber(item.TotalAmount, 0)</td>
                                @*<td>@(item.TypePayment==1? "Chờ thanh toán": "Đã thanh toán")</td>*@
                                @switch (item.TypePayment)
                                {
                                    case 1:
                                        <td>Chờ Thanh Toán</td>
                                        break;
                                    case 2:
                                        <td>Đã Hoàn Thành</td>
                                        break;
                                    case 3:
                                        <td>Thanh Toán Paypal</td>
                                        break;
                                    case 4:
                                        <td>Thanh Toán VNPay</td>
                                        break;
                                    case 5:
                                        <td>Thanh Toán Momo</td>
                                        break;
                                    case 6:
                                        <td>Hủy Đơn Hàng</td>
                                        break;
                                    default:
                                        break;
                                }
                                <td>@item.CreatedDate.ToString("dd/MM/yyyy")</td>
                                <td>
                                    <a href="/admin/order/view/@item.Id" class="btn btn-sm btn-success">Chi tiết</a>
                                    <a href="#" class="btn btn-sm btn-primary btnCapNhat" data-id="@item.Id">Cập nhật</a>
                                </td>
                            </tr>
                            i++;
                        }
                    }
                </tbody>
            </table>
            <div class="row">
                <div class="col-6"></div>
                <div class="col-6" style="text-align:right;">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </div>

            </div>

        </div>
        <!-- /.card-body -->
        <div class="card-footer">
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Cập nhật thanh toán</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="txtOrderId" value="0" />
                <div classs="form-group">
                    <label>Trạng thái</label>
                    <select class="form-control" id="ddTrangThai">
                        <option value="1">
                            Chờ thanh toán
                        </option>
                        <option value="2 ">
                            Đã Hoàn Thành
                        </option>
                        <option value="6">
                            Hủy Đơn Hàng
                        </option>
                        <option value="3 ">
                            Thanh toán Paypal
                        </option>
                        <option value="4 ">
                            Thanh toán VNPay
                        </option>
                        <option value="5 ">
                            Thanh Toán Momo
                        </option>

                    </select>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-primary" id="btnLuu">Lưu lại</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('body').on('click', '.btnCapNhat', function () {
                var id = $(this).data("id");
                $('#txtOrderId').val(id);
                $('#modal-default').modal('show');
            });

            $('body').on('click', '#btnLuu', function () {
                var id = $("#txtOrderId").val();
                var tt = $("#ddTrangThai").val();
                $.ajax({
                    url: '/admin/order/UpdateTT',
                    type: 'POST',
                    data: { id: id, trangthai: tt },
                    success: function (res) {
                        if (res.Success) {
                            location.reload();
                        }
                    }
                });
            });

            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm('Bạn chắc chắn có muốn xoá ?');
                if (conf == true) {
                    $.ajax({
                        url: '/admin/order/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    });
                }
            });

        });

    </script>
}

CosmeticsStore/Areas/Admin/Views/Order/Partial_SanPham.cshtml
@model  IEnumerable<CosmeticsStore.Models.EF.OrderDetail>
@if (Model != null && Model.Any())
{
    int i = 1;
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>STT</th>
                <th>Tên sản phẩm</th>
                <th>Giá</th>
                <th>Số lượng</th>
                <th>Thành tiền</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@i</td>
                    <td>@item.Product.Title</td>
                    <td>@CosmeticsStore.Common.Common.FormatNumber(item.Price, 0)</td>
                    <td>@item.Quantity</td>
                    <td>@CosmeticsStore.Common.Common.FormatNumber((item.Price*item.Quantity), 0)</td>
                </tr>
                i++;
            }
        </tbody>
    </table>
}

CosmeticsStore/Areas/Admin/Views/Order/View.cshtml
@model  CosmeticsStore.Models.EF.Order
@using PagedList;
@{
    ViewBag.Title = "Chi tiết đơn hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/home" class="nav-link"><font color="white">Trang chủ</font></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/order" class="nav-link"><font color="white">Danh sách đơn hàng</font></a>
        </li>
    </ul>
}
<!-- Content Header (Page header) -->
<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Chi tiết đơn hàng</h3>

        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Mã đơn hàng</label>
                        <p class="form-control">@Model.Code</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Họ tên khách hàng</label>
                        <p class="form-control">@Model.CustomerName</p>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Tổng tiền</label>
                        <p class="form-control">@CosmeticsStore.Common.Common.FormatNumber(Model.TotalAmount, 0) đ</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Số điện thoại</label>
                        <p class="form-control">@Model.Phone</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Ngày tạo</label>
                        <p class="form-control">@Model.CreatedDate.ToString("dd/MM/yyyy")</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Địa chỉ</label>
                        <p class="form-control">@Model.Address</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Email</label>
                        <p class="form-control">@Model.Email</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Trạng thái</label>
                        @switch (Model.TypePayment)
                        {
                            case 1:
                                <p class="form-control">Chờ Thanh Toán</p>
                                break;
                            case 2:
                                <p class="form-control">Đã Hoàn Thành</p>
                                break;
                            case 3:
                                <p class="form-control">Thanh Toán Paypal</p>
                                break;
                            case 4:
                                <p class="form-control">Thanh Toán VNPay</p>
                                break;
                            case 5:
                                <p class="form-control">Thanh Toán Momo</p>
                                break;
                            case 6:
                                <p class="form-control">Hủy Đơn Hàng</p>
                                break;
                            default:
                                break;
                        }

                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-12">
                    <h2>Danh sách sản phẩm</h2>
                </div>
                <div class="col-12">
                    @Html.Action("Partial_SanPham", "Order", new { id = Model.Id })
                </div>
            </div>
        </div>
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->